steps:
    #We first need to build and install FreeType
  - script: git clone --depth 1 --branch VER-$(freetypeVersion) https://gitlab.freedesktop.org/freetype/freetype.git $(Pipeline.Workspace)/freetype
    displayName: FreeType Checkout
    workingDirectory: $(Pipeline.Workspace)

  - script: cmake -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=$(Pipeline.Workspace)/freetype/install -D CMAKE_LIBRARY_OUTPUT_DIRECTORY=Release -D BUILD_SHARED_LIBS=true -D FT_DISABLE_HARFBUZZ=TRUE -D FT_DISABLE_BROTLI=TRUE
    displayName: FreeType CMake Setup
    workingDirectory: $(Pipeline.Workspace)/freetype/

  - script: cmake --build build --config Release
    displayName: FreeType CMake Build
    workingDirectory: $(Pipeline.Workspace)/freetype/

  - script: cmake --build build --config Release --target install
    displayName: FreeType CMake Install
    workingDirectory: $(Pipeline.Workspace)/freetype/

    #Now that we have FreeType ready to go, we can build cimgui with it
  - script: git clone --depth 1 --recursive $(Build.Repository.Uri) $(Pipeline.Workspace)/cimgui
    displayName: cimgui Checkout
    workingDirectory: $(Pipeline.Workspace)

  - script: cmake -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_LIBRARY_OUTPUT_DIRECTORY=Release -D freetype_DIR=$(Pipeline.Workspace)/freetype/install/lib/cmake/freetype/
    displayName: cimgui CMake Setup
    workingDirectory: $(Pipeline.Workspace)/cimgui/

  - script: cmake --build build --config Release
    displayName: cimgui CMake Build
    workingDirectory: $(Pipeline.Workspace)/cimgui/